name: Ruff Job
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
jobs:
  ruff_job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@6
        with:
          python-version: '3.13'

      - name: Install Ruff
        run: pip install ruff

      - name: Start ruff Check
        run: ruff check --show-fixes > results.txt

      - name: Send Results
        uses: marocchino/sticky-pull-request-comment@v3
        with:
          path: results.txt
          message: |
            Результаты проверки кода этого PR с помощью ruff:
            ```
            {{{content}}}
            ```

      - name: Finish Job
        if: always()
        run: echo Ruff Job Has Finished
